config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "user#redirect_to_timeline"

  get "/timeline" => "tweet#timeline", as: :timeline

  get "/users" => "user#index", as: :tweet_users

  get "/users/:id" => "user#show", as: :user

  # get "/users/profile" => "user#profile"

  get "/users/follow/:id" => "user#follow", as: :follow_user

  get "/users/unfollow/:id" => "user#unfollow", as: :unfollow_user

  post "/tweet/create" => "tweet#create", as: :create_tweet

  delete "/tweet/delete/:id" => "tweet#delete", as: :delete_tweet

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  belongs_to :user

  default_scope { order(created_at: :desc) }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets

  mount_uploader :avatar, AvatarUploader

  serialize :following, Array

  validates :username, uniqueness: true

  def location
    "#{city}, #{state}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    keys = [:username, :name, :email, :password, :password_confirmation, :city, :state, :bio, :avatar]
    devise_parameter_sanitizer.permit(:sign_up, keys: keys)
    devise_parameter_sanitizer.permit(:account_update, keys: keys)
  end
  
end

app/controllers/tweet_controller.rb
class TweetController < ApplicationController

  before_action :authenticate_user!, except: [:index]

  def index
  end

  def timeline
    ids = current_user.following
    ids.push(current_user.id.to_s)
    ids.each do |id|
      if User.find_by(id: id.to_i) == nil
        ids.delete(id)
      end
    end
    @tweets = Tweet.where(user_id: ids).order(created_at: :desc)
  end

  def create
   tweet = current_user.tweets.create(tweet_params)
   tweet.save!
   redirect_to user_path(id: current_user.id)
  end

  def delete
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to user_path(id: current_user.id)
  end

  private

  def tweet_params
    params.require(:tweet).permit(:message)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tweet = Tweet.new
  end

  # def profile
  #   @user = current_user
  #   @tweets = Tweet.where(user_id: current_user.following.push(current_user.id))
  #   @tweet = Tweet.new
  # end

  def follow
    current_user.following.push(params[:id])
    current_user.save!
    redirect_to user_url(id: params[:id])
  end

  def unfollow
    current_user.following.delete(params[:id])
    current_user.save!
    redirect_to user_url(id: params[:id])
  end

  def redirect_to_timeline
    redirect_to timeline_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end

end

app/helpers/tweet_helper.rb
module TweetHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Q's Social Site</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in?  %>
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <%= link_to "Timeline", timeline_url, class: "navbar-text" %>
            <%= link_to "Users", tweet_users_url, class: "navbar-text" %>
            <%= link_to "Profile", user_url(id: current_user.id), class: "navbar-text" %>
              <p class="navbar-user-info">
                Signed in as @<%= current_user.username %> <span> </span>
                <%= link_to "Sign Out", destroy_user_session_url, method: :delete, class: "btn btn-primary navbar-btn" %>
              </p>
        </div>
      </nav>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %> <!-- this is where all of the other views are rendered -->
    </div>
  </body>

</html>

app/views/shared/_tweet.html.erb
<div class="well">
  <p><%= image_tag tweet.user.avatar.url %> <%= link_to "@#{tweet.user.username}", user_url(id: tweet.user.id) %></p>
  <p><%= time_ago_in_words(tweet.created_at) %> ago</p>
  <p><%= tweet.message %></p>
</div>

app/views/tweet/timeline.html.erb
<% current_user.following.delete(current_user.id.to_s) %>
  <% if current_user.following == [] %>
    <h4>Click on the links above to get started by following other users and writing your own posts!</h4>
  <% end %>
<% current_user.following.push(current_user.id.to_s) %>

<div class="timeline-tweets">
  <% @tweets.each do |tweet| %>
    <div class="well">
      <p>
        <% if tweet.user.avatar.url %> <!-- this returns true if the user has uploaded a photo -->
          <%= image_tag tweet.user.avatar.url, width: 150 %>
        <% else %>
          <%= image_tag 'blank-profile-pic.jpg', width: 150 %>
        <% end %>
        <%= link_to "@#{tweet.user.username}", user_url(id: tweet.user.id) %>
      </p>
      <p><%= time_ago_in_words(tweet.created_at) %> ago</p>
      <p><%= tweet.message %></p>
    </div>
  <% end %>
</div>

app/views/user/_new_tweet.html.erb
<div class="tweet-form">
  <%= form_for tweet, url: create_tweet_url do |f| %>
  <br>
  <%= f.text_area :message, autofocus: true, cols: 99, rows: 7 %>
  <br>
  <%= f.submit "Post It!", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/user/index.html.erb
<br>

<div class="users">
  <% @users.in_groups_of(3, false) do |group| %> <!-- look here for more info on the "false"... https://makandracards.com/makandra/976-split-an-array-into-groups -->
    <div class="row">
      <% group.each do |user| %>
        <div class="col-xs-12 col-sm-12 col-md-4">
          <div class="thumbnail">
            <% if user.avatar.url %> <!-- this returns true if the user has uploaded a photo -->
              <%= image_tag user.avatar.url, width: 150 %>
            <% else %>
              <%= image_tag 'blank-profile-pic.jpg', width: 150 %>
            <% end %>
            <div class="caption">
              <%= link_to "@#{user.username}", user_url(id: user.id) %>
              <br>
              <%= user.name %>
              <br>
              <%= user.city %>, <%= user.state %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/user/show.html.erb
<div class="col-md-4">
  <div class="profile-pic">
    <% if @user.avatar.url %> <!-- this returns true if the user has uploaded a photo -->
      <%= image_tag @user.avatar.url, width: 150 %>
    <% else %>
      <%= image_tag 'blank-profile-pic.jpg', width: 150 %>
    <% end %>
  </div>
  <div class="profile-info">
    <h3>@<%= @user.username %></h3>
    <p><strong>Name:</strong> <%= @user.name %></p>
    <p><strong>City:</strong> <%= @user.city %>, <%= @user.state %></p>
    <p><strong>Email:</strong> <%= @user.email %></p>
    <p><strong>Bio:</strong> <%= @user.bio %></p>
  </div>
  <div class="follow-button">
    <% if @user != current_user %>
      <% if current_user.following.include?(@user.id.to_s) %>
        <%= link_to "Unfollow", unfollow_user_url(id: @user.id), class: "btn btn-primary", id: "unfollow_btn" %>
      <% else %>
        <%= link_to "Follow", follow_user_url(id: @user.id), class: "btn btn-primary" %>
      <% end %>
    <% else %>
      <%= link_to "Edit Profile", edit_user_registration_url, method: :get, class: "btn btn-primary navbar-btn" %>
    <% end %>
  </div>
</div>

<div class="col-md-8">
  <% if current_user.following.include?(@user.id.to_s) || current_user == @user %>
    <div class="profile-tweets">
      <% if @user == current_user %>
        <%= render 'new_tweet', tweet: @tweet %>
      <% end %>
      <% @user.tweets.each do |tweet| %>
        <div class="well">
          <p><%= link_to "@#{tweet.user.username}", user_url(id: tweet.user.id) %>
          <% if current_user == tweet.user %>
            <%= link_to "Delete", delete_tweet_url(id: tweet.id), method: :delete, class: "btn btn-default btn-md" %>
          <% end %></p>
          <p><%= time_ago_in_words(tweet.created_at) %> ago</p>
          <p><%= tweet.message %></p>
        </div>
      <% end %>
    </div>
  <% else %>
    <h4>You must click the follow button to see this user's posts.  Go ahead, don't be shy!</h4>
  <% end %>
</div>